# Generated by Django 4.0.2 on 2022-02-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_onhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimda',
            name='onhome',
            field=models.BooleanField(default=False),
        ),
    ]
